version: '3.8'

services:
  app:
    build:
      context: ../..
      dockerfile: docker/app/Dockerfile.${BUILD_MODE:-prod}
      args:
        BUILD_MODE: ${BUILD_MODE:-prod}
    container_name: ${COMPOSE_PROJECT_NAME:-my-stack}-app
    restart: unless-stopped
    ports:
      - "${APP_PORT:-8000}:8000"
    environment:
      - BUILD_MODE=${BUILD_MODE:-prod}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s