name: firecrawl

x-common-service: &common-service
  image: ghcr.io/firecrawl/firecrawl

  ulimits:
    nofile:
      soft: 65535
      hard: 65535
  extra_hosts:
    - "host.docker.internal:host-gateway"

x-common-env: &common-env
  REDIS_URL: ${REDIS_URL:-redis://my-stack-redis:6379}
  REDIS_RATE_LIMIT_URL: ${REDIS_URL:-redis://my-stack-redis:6379}
  PLAYWRIGHT_MICROSERVICE_URL: ${PLAYWRIGHT_MICROSERVICE_URL:-http://playwright-service:3000/scrape}
  NUQ_DATABASE_URL: postgres://postgres:postgres@nuq-postgres:5432/postgres
  USE_DB_AUTHENTICATION: ${USE_DB_AUTHENTICATION}
  OPENAI_API_KEY: ${OPENAI_API_KEY}
  OPENAI_BASE_URL: ${OPENAI_BASE_URL}
  MODEL_NAME: ${MODEL_NAME}
  MODEL_EMBEDDING_NAME: ${MODEL_EMBEDDING_NAME}
  OLLAMA_BASE_URL: ${OLLAMA_BASE_URL}
  LOGGING_LEVEL: ${LOGGING_LEVEL}
  PROXY_SERVER: ${PROXY_SERVER}
  PROXY_USERNAME: ${PROXY_USERNAME}
  PROXY_PASSWORD: ${PROXY_PASSWORD}
  SEARXNG_ENDPOINT: ${SEARXNG_ENDPOINT:-http://searxng:8080}
  SEARXNG_ENGINES: ${SEARXNG_ENGINES:-google,bing,duckduckgo}
  SEARXNG_CATEGORIES: ${SEARXNG_CATEGORIES:-general,science}

services:
  playwright-service:
    image: ghcr.io/firecrawl/playwright-service:latest
    environment:
      PORT: 3000
      PROXY_SERVER: ${PROXY_SERVER}
      PROXY_USERNAME: ${PROXY_USERNAME}
      PROXY_PASSWORD: ${PROXY_PASSWORD}
      BLOCK_MEDIA: ${BLOCK_MEDIA}

  api:
    <<: *common-service
    environment:
      <<: *common-env
      HOST: "0.0.0.0"
      PORT: ${INTERNAL_PORT:-3002}
      EXTRACT_WORKER_PORT: ${EXTRACT_WORKER_PORT:-3004}
      WORKER_PORT: ${WORKER_PORT:-3005}
      ENV: local
    env_file:
      - env/${ENVIRONMENT:-dev}.env
    depends_on:
      - playwright-service
    # Expose port to traefik network only
    expose:
      - "${INTERNAL_PORT:-3002}"
    command: node dist/src/harness.js --start-docker
    networks:
      - shared-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firecrawl.rule=Host(`firecrawl.${BASE_DOMAIN:-localhost}`)"
      - "traefik.http.services.firecrawl.loadbalancer.server.port=${INTERNAL_PORT:-3002}"
      # - "traefik.http.routers.firecrawl.tls=true"
      # - "traefik.http.routers.firecrawl.tls.certresolver=${TLS_CERT_RESOLVER:-selfsigned}"

  # Redis service disabled - using shared redis from main docker-compose.yml
  # redis:
  #   image: redis:alpine
  #   networks:
  #     - shared-network
  #   command: redis-server --bind 0.0.0.0
  
  nuq-postgres:
    image: ghcr.io/firecrawl/nuq-postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    # Removed port mapping to avoid conflicts - postgres is internal only
    # ports:
    #   - "5432:5432"
    networks:
      - shared-network

