# =============================================================================
# AI Assistant Docker Compose Configuration
# =============================================================================
# Usage examples:
# - Development: docker compose --profile dev up
# - Production: docker compose up
# - With Firecrawl: docker compose --profile firecrawl up
# - With optional services: docker compose --profile dev --profile monitoring up

networks:
  ai-assistant-network:
    driver: bridge

volumes:
  redis_data:
    driver: local
  postgres_data:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local
  searxng_static:
    driver: local
  firecrawl_redis_data:
    driver: local
  jina_reranker_logs:
    driver: local
  milvus_data:
    driver: local

services:
  firecrawl:
    image: ghcr.io/firecrawl/firecrawl:latest
    container_name: firecrawl
    environment:
      - PORT=3002
      - HOST=0.0.0.0
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/ai_assistant?options=--search_path%3Dfirecrawl
      - POSTGRES_DB_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/ai_assistant?options=--search_path%3Dfirecrawl
      - POSTGRES_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/ai_assistant?options=--search_path%3Dfirecrawl
      - DATABASE_HOST=postgres
      - DATABASE_PORT=5432
      - DATABASE_NAME=ai_assistant
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=${POSTGRES_PASSWORD}
      - REDIS_URL=redis://redis:6379/1
      - USE_DB_AUTHENTICATION=false
      - USE_DB=false
      - BULL_AUTH_KEY=${FIRECRAWL_BULL_AUTH_KEY:-change_me_firecrawl}
      - RATE_LIMIT_MAX_REQUESTS=100
      - RATE_LIMIT_WINDOW_MS=60000
    depends_on:
      - postgres
      - redis
    networks:
      - ai-assistant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - production
      - dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.firecrawl.rule=PathPrefix(`/firecrawl`)"
      - "traefik.http.routers.firecrawl.entrypoints=web"
      - "traefik.http.routers.firecrawl.middlewares=security-headers@file,rate-limit@file"
      - "traefik.http.services.firecrawl.loadbalancer.server.port=3002"

  # =============================================================================
  # Jina Reranker Service
  # =============================================================================

  # Jina AI Reranker Service
  jina-reranker:
    build:
      context: ./config/jina-reranker
      dockerfile: Dockerfile
    container_name: ai-assistant-jina-reranker
    environment:
      - JINA_API_KEY=${JINA_API_KEY}
      - REDIS_URL=redis://redis:6379/1
      - CONFIG_PATH=/app/config.yml
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - jina_reranker_logs:/app/logs
      - ./config/jina-reranker/config.yml:/app/config.yml
    networks:
      - ai-assistant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    profiles:
      - production
      - dev
    labels:
      # Traefik routing for external access
      - "traefik.enable=true"
      - "traefik.http.routers.jina-reranker.rule=PathPrefix(`/rerank`)"
      - "traefik.http.routers.jina-reranker.priority=300"
      - "traefik.http.routers.jina-reranker.entrypoints=web"
      - "traefik.http.routers.jina-reranker.middlewares=security-headers@file,rate-limit@file,compression@file"
      - "traefik.http.services.jina-reranker.loadbalancer.server.port=8080"

  # =============================================================================
  # Milvus Vector Database Service
  # =============================================================================

  # Etcd for Milvus metadata storage
  etcd:
    container_name: milvus-etcd
    image: quay.io/coreos/etcd:v3.5.5
    environment:
      - ETCD_AUTO_COMPACTION_MODE=revision
      - ETCD_AUTO_COMPACTION_RETENTION=1000
      - ETCD_QUOTA_BACKEND_BYTES=4294967296
      - ETCD_SNAPSHOT_COUNT=50000
    volumes:
      - milvus_data:/etcd
    command: etcd -advertise-client-urls=http://127.0.0.1:2379 -listen-client-urls http://0.0.0.0:2379 --data-dir /etcd
    healthcheck:
      test: ["CMD", "etcdctl", "endpoint", "health"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ai-assistant-network
    profiles:
      - production
      - dev
    labels:
      - "traefik.enable=false"  # Internal service only

  # MinIO for Milvus object storage
  minio:
    container_name: milvus-minio
    image: minio/minio:RELEASE.2023-03-20T20-16-18Z
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9001:9001"
    volumes:
      - milvus_data:/minio_data
    command: minio server /minio_data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - ai-assistant-network
    profiles:
      - production
      - dev
    labels:
      - "traefik.enable=false"  # Internal service only

  # Milvus vector database
  milvus:
    container_name: milvus-standalone
    image: milvusdb/milvus:v2.4.0
    command: ["milvus", "run", "standalone"]
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_ENDPOINTS: etcd:2379
      MINIO_ADDRESS: minio:9000
    volumes:
      - milvus_data:/var/lib/milvus
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      start_period: 90s
      timeout: 20s
      retries: 3
    ports:
      - "19530:19530"
      - "9091:9091"
    depends_on:
      - "etcd"
      - "minio"
    networks:
      - ai-assistant-network
    profiles:
      - production
      - dev
    labels:
      - "traefik.enable=false"  # Internal service only

  # =============================================================================
  # Core Services
  # =============================================================================

  # Main AI Assistant Application
  ai-assistant:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-assistant
    environment:
      - HOST=0.0.0.0
      - PORT=8000
      - ENVIRONMENT=production
      - REDIS_URL=redis://redis:6379/0
      - SEARXNG_URL=http://searxng:8080
      - BASE_URL=${BASE_URL:-http://localhost}
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/ai_assistant
      - MULTI_WRITER_POSTGRESQL_CONNECTION_STRING=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/ai_assistant?options=--search_path%3Dmulti_writer
    env_file:
      - .env.dev
    depends_on:
      redis:
        condition: service_healthy
      searxng:
        condition: service_healthy
      milvus:
        condition: service_healthy
      postgres:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
      - searxng_static:/usr/local/searxng/searx/static:ro
    networks:
      - ai-assistant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - production # ONLY in production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai-assistant.rule=PathPrefix(`/`) && !PathPrefix(`/chat`)"
      - "traefik.http.routers.ai-assistant.priority=1"
      - "traefik.http.routers.ai-assistant.entrypoints=web"
      - "traefik.http.routers.ai-assistant.middlewares=security-headers@file,rate-limit@file,compression@file"

  # Redis for caching
  redis:
    image: redis:7.2-alpine
    container_name: ai-assistant-redis
    volumes:
      - redis_data:/data
    networks:
      - ai-assistant-network
    restart: unless-stopped
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # SearXNG for web search capabilities
  searxng:
    image: searxng/searxng:latest
    container_name: ai-assistant-searxng
    networks:
      - ai-assistant-network
    restart: unless-stopped
    # ADD THIS: Creates a temporary, writable, in-memory filesystem at /run.
    # This allows the container's startup scripts to create sockets and pidfiles
    # without failing on a read-only filesystem. The "exec" option is required
    # by some startup processes.
    tmpfs:
      - /run:exec
      - /tmp
    ports:
      - "8088:8080"
    volumes:
      # Keep these as read-only, which is a security best practice.
      - ./config/searxng/settings.yml:/etc/searxng/settings.yml:ro
      - ./config/searxng/limiter.toml:/etc/searxng/limiter.toml:ro
      - ./config/searxng/plugins.yml:/etc/searxng/plugins.yml:ro
      - searxng_static:/usr/local/searxng/searx/static
    environment:
      - BASE_URL=/search
      - BIND_ADDRESS=0.0.0.0
      - PORT=8080
      - SEARXNG_SECRET_KEY=${SEARXNG_SECRET_KEY:-change-this-secret-key}
      - SEARXNG_INSTANCE_NAME=${SEARXNG_INSTANCE_NAME:-AI Assistant Search}
      - SEARXNG_THEME=${SEARXNG_THEME:-simple}
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    profiles:
      - production
      - dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=PathPrefix(`/search`)"
      - "traefik.http.routers.searxng.priority=200"
      - "traefik.http.routers.searxng.entrypoints=web"
      # - "traefik.http.routers.searxng.middlewares=searxng-stripprefix@file" # <-- ADD THIS
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"

  # =============================================================================
  # Production Services
  # =============================================================================

  # Production Traefik Reverse Proxy
  traefik:
    image: traefik:v3.0
    container_name: ai-assistant-traefik
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.traefik.address=:8080"
      - "--log.level=WARN"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      - "--ping=true"
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/docker/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/docker/middlewares.yml:/etc/traefik/dynamic/middlewares.yml:ro
      - ./config/docker/traefik-prod.yml:/etc/traefik/traefik-prod.yml:ro
    env_file:
      - .env
    networks:
      - ai-assistant-network
    healthcheck:
      test: ["CMD", "traefik", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    profiles:
      - production # ONLY in production
  # =============================================================================
  # Development Profile
  # =============================================================================

  # Development AI Assistant
  ai-assistant-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-assistant-dev
    volumes:
      - .:/app
      - ./logs:/app/logs
      - /app/.venv
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - RELOAD=true
      - REDIS_URL=redis://redis:6379/0
      - SEARXNG_URL=http://searxng:8080
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/ai_assistant
      - MULTI_WRITER_POSTGRESQL_CONNECTION_STRING=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/ai_assistant?options=--search_path%3Dmulti_writer
    env_file:
      - .env.dev
    depends_on:
      redis:
        condition: service_healthy
      searxng:
        condition: service_healthy
      milvus:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - ai-assistant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/monitoring/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    command: ["uv", "run", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    profiles:
      - dev # ONLY in dev
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ai-assistant-dev.rule=PathPrefix(`/`) && !PathPrefix(`/search`) && !PathPrefix(`/chat`)"
      - "traefik.http.routers.ai-assistant-dev.priority=100"
      - "traefik.http.routers.ai-assistant-dev.entrypoints=web"
      - "traefik.http.services.ai-assistant-dev.loadbalancer.server.port=8000"

  # Development Traefik
  traefik-dev:
    image: traefik:v3.0
    container_name: ai-assistant-traefik-dev
    restart: unless-stopped
    ports:
      - "8000:80"
      - "8080:8080"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.forwardedheaders.insecure"
      - "--entrypoints.traefik.address=:8080"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--metrics.prometheus=true"
      - "--ping=true"
      - "--global.checkNewVersion=false"
      - "--global.sendAnonymousUsage=false"
      - "--ping.entrypoint=traefik"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/docker/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./config/docker/middlewares.yml:/etc/traefik/dynamic/middlewares.yml:ro
    networks:
      - ai-assistant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    profiles:
      - dev # ONLY in dev

  # Chainlit Interface Service
  chainlit:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: ai-assistant-chainlit
    volumes:
      - .:/app  # Mount source code for hot reload
      - ./logs:/app/logs
      # Exclude .venv to prevent Docker from using host's virtual environment
      - /app/.venv
    environment:
      - ENVIRONMENT=development
      - DEBUG=true
      - RELOAD=true
      - REDIS_URL=redis://redis:6379/0  # Override for Docker network
      - SEARXNG_URL=http://searxng:8080   # Override for Docker network
      - HOST=0.0.0.0
      - PORT=8001
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/ai_assistant
      - MULTI_WRITER_POSTGRESQL_CONNECTION_STRING=postgresql://postgres:${POSTGRES_PASSWORD}@postgres:5432/ai_assistant?options=--search_path%3Dmulti_writer
    env_file:
      - .env.dev
    depends_on:
      redis:
        condition: service_healthy
      searxng:
        condition: service_healthy
      milvus:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - ai-assistant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "-O-", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 120s
    command: ["uv", "run", "chainlit", "run", "chainlit_app.py", "--host", "0.0.0.0", "--port", "8001"]
    profiles:
      - dev
      - production
    labels:
      # Development Traefik routing for Chainlit
      - "traefik.enable=true"
      - "traefik.http.routers.chainlit.rule=PathPrefix(`/chat`) || PathPrefix(`/assets`) || PathPrefix(`/auth`) || PathPrefix(`/user`) || PathPrefix(`/project`) || PathPrefix(`/favicon`) || PathPrefix(`/ws`)"
      - "traefik.http.routers.chainlit.priority=150"
      - "traefik.http.routers.chainlit.entrypoints=web"
      - "traefik.http.routers.chainlit.middlewares=chainlit-websocket@file"
      - "traefik.http.routers.chainlit.service=chainlit"
      - "traefik.http.services.chainlit.loadbalancer.server.port=8001"
      - "traefik.http.services.chainlit.loadbalancer.sticky.cookie=true"
      - "traefik.http.services.chainlit.loadbalancer.sticky.cookie.name=chainlit-session"


  # Redis Commander for Redis GUI
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: ai-assistant-redis-commander
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - ai-assistant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://0.0.0.0:8081/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    profiles:
      - dev
    labels:
      # Development Traefik routing for Redis Commander
      - "traefik.enable=true"
      - "traefik.http.routers.redis-commander.rule=PathPrefix(`/redis`)"
      - "traefik.http.routers.redis-commander.entrypoints=web"
      - "traefik.http.services.redis-commander.loadbalancer.server.port=8081"

  # =============================================================================
  # Optional Services (can be enabled with any profile)
  # =============================================================================

  postgres:
    image: postgres:15-alpine
    container_name: ai-assistant-postgres
    environment:
      - POSTGRES_DB=ai_assistant
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./config/postgres/init-supabase.sql:/docker-entrypoint-initdb.d/init-supabase.sql:ro
    networks:
      - ai-assistant-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
    profiles:
      - dev        # Available in dev
      - production # Available in production


  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: ai-assistant-prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - ai-assistant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    profiles:
      - production
      - dev

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: ai-assistant-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./config/monitoring/grafana/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      prometheus:
        condition: service_healthy
    networks:
      - ai-assistant-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    profiles:
      - production
      - dev