name: frontend

services:
  frontend:
    build:
      context: ../../frontend
      dockerfile: ../docker/frontend/Dockerfile.prod
    container_name: ${COMPOSE_PROJECT_NAME:-my-stack}-frontend-prod
    restart: unless-stopped
    expose:
      - "80"
    environment:
      - NODE_ENV=production
      - REACT_APP_API_URL=http://supabase.localhost
    networks:
      - shared-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`frontend.${BASE_DOMAIN:-localhost}`)"
      - "traefik.http.services.frontend.loadbalancer.server.port=80"
      - "traefik.http.routers.frontend.tls=true"
      - "traefik.http.routers.frontend.tls.certresolver=${TLS_CERT_RESOLVER:-selfsigned}"