name: searxng

volumes:
  searxng-data:
    driver: local

services:
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: ${COMPOSE_PROJECT_NAME:-my-stack}-searxng
    restart: unless-stopped
    environment:
      - SEARXNG_BASE_URL=${SEARXNG_BASE_URL:-https://searxng.localhost/}
    volumes:
      - ./searxng:/etc/searxng:rw
      - searxng-data:/var/cache/searxng:rw
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - shared-network
    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.searxng.rule=Host(`searxng.${BASE_DOMAIN:-localhost}`)"
      - "traefik.http.services.searxng.loadbalancer.server.port=8080"
