http:
  middlewares:
    security-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "DENY"

    rate-limit:
      rateLimit:
        average: 100
        period: 1m
        burst: 200

    compression:
      compress:
        excludedContentTypes:
          - text/event-stream
          - application/grpc
        minResponseBodyBytes: 1024

    searxng-stripprefix:
      stripprefix:
        prefixes:
          - "/search"
    
    redis-stripprefix:
      stripprefix:
        prefixes:
          - "/redis"
    
    chainlit-websocket:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        accessControlAllowHeaders:
          - "*"
        accessControlAllowOrigins:
          - "*"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
