http:
  middlewares:
    security-headers:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        customResponseHeaders:
          X-Content-Type-Options: "nosniff"
          X-Frame-Options: "DENY"

    rate-limit:
      rateLimit:
        average: 100
        period: 1m
        burst: 200

    compression:
      compress:
        excludedContentTypes:
          - text/event-stream
          - application/grpc
        minResponseBodyBytes: 1024

    searxng-stripprefix:
      stripprefix:
        prefixes:
          - "/search"
    
    redis-stripprefix:
      stripprefix:
        prefixes:
          - "/redis"
    
    chainlit-stripprefix:
      stripprefix:
        prefixes:
          - "/chat"
    
    chainlit-websocket:
      headers:
        customRequestHeaders:
          X-Forwarded-Proto: "https"
        accessControlAllowOriginList:
          - "http://localhost:8000"
          - "http://127.0.0.1:8000"
          - "*"
        accessControlAllowHeaders:
          - "Content-Type"
          - "Authorization"
          - "X-Requested-With"
          - "Accept"
          - "Origin"
          - "Access-Control-Request-Method"
          - "Access-Control-Request-Headers"
        accessControlAllowMethods:
          - "GET"
          - "POST"
          - "PUT"
          - "DELETE"
          - "OPTIONS"
          - "HEAD"
          - "PATCH"
        accessControlMaxAge: 86400
        addVaryHeader: true
        accessControlAllowCredentials: true