[botdetection.ip_limit]
# Basic IP filtering
filter_link_local = false

[botdetection.ip_lists]
# Allow Docker networks and localhost
pass_ip = [
    "127.0.0.0/8",
    "::1/128", 
    "172.16.0.0/12",
    "10.0.0.0/8",
    "192.168.0.0/16"
]
# Block known bad IPs (empty for now)
block_ip = []