use_default_settings: true

general:
  debug: false
  instance_name: "AI Assistant Search"
  contact_url: false
  enable_metrics: false

search:
  safe_search: 1
  autocomplete: "google"
  default_lang: "auto"
  ban_time_on_fail: 5
  max_ban_time_on_fail: 120

server:
  port: 8080
  bind_address: "0.0.0.0"
  secret_key: "${SEARXNG_SECRET_KEY}"
  base_url: "http://searxng:8080/"
  image_proxy: true
  limiter: true
  public_instance: false

ui:
  static_use_hash: true
  default_locale: "en"
  theme_args:
    simple_style: "dark"

redis:
  url: redis://redis:6379/0

engines:
  - name: google
    engine: google
    use_mobile_ui: false
  - name: bing
    engine: bing
  - name: duckduckgo
    engine: duckduckgo
  - name: wikipedia
    engine: wikipedia
  - name: brave
    engine: brave