# see https://docs.searxng.org/admin/settings/settings.html#settings-use-default-settings
use_default_settings: true
server:
  # base_url is defined in the SEARXNG_BASE_URL environment variable, see .env and docker-compose.yml
  secret_key: "05d2d0453328aa3c47ea4415612a6e51044cb2c115e192ada2a0e3503377d724"  # change this!
  limiter: false  # enable this when running the instance for a public usage on the internet
  image_proxy: true
redis:
  url: redis://redis:6379/0
# Disable external engines that require network access
search:
  formats:
    - html
  engines:
    - name: google
      disabled: false
    - name: bing
      disabled: false
    - name: duckduckgo
      disabled: false
    - name: wikipedia
      disabled: false
    - name: wikidata
      disabled: true
    - name: ahmia
      disabled: true
    - name: yacy
      disabled: true
    - name: torch
      disabled: true
