_format_version: "1.1"

services:
  - name: auth-api
    url: http://supabase-auth:9999
    plugins:
      - name: cors
      - name: key-auth
    routes:
      - name: auth-route
        paths:
          - /auth/v1/
        strip_path: false

  - name: rest-api
    url: http://supabase-rest:3000
    plugins:
      - name: cors
      - name: jwt
        config:
          secret_is_base64: false
    routes:
      - name: rest-route
        paths:
          - /rest/v1/
        strip_path: false

  - name: realtime-api
    url: http://supabase-realtime:4000
    plugins:
      - name: cors
    routes:
      - name: realtime-route
        paths:
          - /realtime/v1/
        strip_path: false

  - name: storage-api
    url: http://supabase-storage:5000
    plugins:
      - name: cors
    routes:
      - name: storage-route
        paths:
          - /storage/v1/
        strip_path: false

consumers:
  - username: anon
    keyauth_credentials:
      - key: ${SUPABASE_ANON_KEY}
  - username: service_role
    keyauth_credentials:
      - key: ${SUPABASE_SERVICE_ROLE_KEY}

plugins:
  - name: cors
    config:
      origins:
        - "*"
      methods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      headers:
        - Accept
        - Accept-Version
        - Content-Length
        - Content-MD5
        - Content-Type
        - Date
        - Authorization
        - apikey
        - X-Client-Info
        - X-Request-ID