# Prometheus configuration for AI Assistant monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # AI Assistant application
  - job_name: 'ai-assistant'
    static_configs:
      - targets: ['ai-assistant:8000']
    metrics_path: '/metrics'
    scrape_interval: 10s

  # Redis metrics (if redis_exporter is added)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s

  # Node Exporter (if added for system metrics)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Jina Reranker service
  - job_name: 'jina-reranker'
    static_configs:
      - targets: ['jina-reranker:8080']
    metrics_path: '/metrics'
    scrape_interval: 30s
    scrape_timeout: 10s